name: 'deploy'

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        name: 'Build'
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2

            - name : "Configure git"
              run : |
                  git config "user.name" "github-actions"
                  git config "user.email" "public-dev-github-actions-niolesk@gissehel.org"

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
          
            - name: "build"
              if: "contains(github.ref, 'refs/tags')"
              run: |
                  yarn
                  yarn build
                  echo "niolesk.top" > build/CNAME
                  yarn build-storybook
                  mv storybook-static build/storybook

            - name: Deploy to GitHub Pages
              if: success()
              uses: crazy-max/ghaction-github-pages@v2
              with:
                target_branch: gh-pages
                build_dir: build
              env:
                GITHUB_TOKEN: ${{ secrets.DEPLOY_PAT }}

