name: 'deploy'

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        name: 'Build'
        runs-on: node:alpine
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2

            - name: "build / deploy if tag"
              if: "contains(github.ref, 'refs/tags')"
              run: |
                  yarn
                  yarn deploy

