name: 'deploy'

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        name: 'Build'
        runs-on: ubuntu-latest
        steps:
            - name : "Configure git"
              run : |
                  git config "user.name" "github-actions"
                  git config "user.email" "public-dev-github-actions-niolesk@gissehel.org"

            - name: "Checkout"
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
          
            - name: "build / deploy if tag"
              if: "contains(github.ref, 'refs/tags')"
              run: |
                  yarn
                  yarn deploy

