name: 'deploy'

on:
    push:
        tags:
            - 'v*'

jobs:
    deploy:
        name: 'Deploy'
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2

            - name : "Configure git"
              run : |
                  git config "user.name" "github-actions"
                  git config "user.email" "public-dev-github-actions-niolesk@gissehel.org"

            - name: "Setup node"
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
          
            - name: "Build"
              run: |
                  yarn
                  yarn build
                  yarn build-storybook

            - name: "Create Niolesk assets"
              run: |
                  ref="${{ github.ref }}"

                  site_name="niolesk-site-${ref#refs/tags/v*}"
                  storybook_name="niolesk-storybook-${ref#refs/tags/v*}"

                  mv "build" "${site_name}"
                  zip -r "${site_name}.zip" "${site_name}"
                  tar cvzf "${site_name}.tar.gz" "${site_name}"
                  mv "${site_name}" build

                  mv "storybook-static" "${storybook_name}"
                  zip -r "${storybook_name}.zip" "${storybook_name}"
                  tar cvzf "${storybook_name}.tar.gz" "${storybook_name}"
                  mv "${storybook_name}" storybook

            - name: "Move storybook to build dir"
              run: |
                  echo "niolesk.top" > build/CNAME
                  mv storybook build/storybook
                  touch build/.nojekyll

            - name: "Deploy to GitHub Pages"
              if: success()
              uses: crazy-max/ghaction-github-pages@v2
              with:
                target_branch: gh-pages
                build_dir: build
              env:
                GITHUB_TOKEN: ${{ secrets.DEPLOY_PAT }}

            - name: "Create release"
              if: success()
              uses: "softprops/action-gh-release@v1"
              with:
                  files: |
                    niolesk-*.zip
                    niolesk-*.tar.gz
                  draft: false
                  prerelease: false
